version: '3'

services:
  
  app:
    container_name: app
    restart: always
    build: ./plotly
    ports:
      - "8000:8000"
    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:8000 app:server


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app